# Generated by Django 2.1.5 on 2020-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_of_work',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
