# Generated by Django 2.1.5 on 2020-07-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificateApp', '0002_project_detail_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='certificateApp.UserProfile')),
            ],
        ),
    ]
