# Generated by Django 2.1.1 on 2020-07-06 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_pdf', models.FileField(default='default.pdf', upload_to='certificates/pdf')),
                ('certificate_png', models.FileField(default='default.png', upload_to='certificates/png')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_contact_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('pan_number', models.CharField(max_length=20)),
                ('aadhaar', models.CharField(max_length=20)),
                ('emergency_contact_no', models.CharField(max_length=15)),
                ('bank_account_no', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('biometric_id_number', models.CharField(max_length=225)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('end_date', models.DateField()),
                ('upload_traker_link', models.URLField()),
                ('detail_of_work', models.TextField()),
                ('mentor_or_leader', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.ProfileChoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWorkedChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_worked', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('upload_report', models.FileField(upload_to='reports')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='TenureChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfInternChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_intern', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('registration_number', models.CharField(editable=False, max_length=225, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_worked_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.ProjectWorkedChoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.StatusChoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.TenureChoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='certificate_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='internship_tenure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.TenureChoice'),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.ProfileChoice'),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.ProjectWorkedChoice'),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='type_of_internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.TypeOfInternChoice'),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.UserProfile'),
        ),
    ]
