# Generated by Django 2.1.1 on 2020-07-04 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=12)),
                ('whatsapp_no', models.CharField(max_length=12)),
                ('project', models.CharField(choices=[('emp1', 'Exm1'), ('emp2', 'Exm2')], max_length=15)),
                ('profile', models.CharField(choices=[('emp1', 'Exm1'), ('emp2', 'Exm2')], max_length=12)),
                ('typeofInternship', models.CharField(choices=[('emp1', 'Exm1'), ('emp2', 'Exm2')], max_length=15)),
                ('joiningDate', models.DateField(auto_now_add=True)),
                ('panNumber', models.CharField(max_length=10)),
                ('aadharNumber', models.CharField(max_length=12)),
                ('emergencyContactNumber', models.CharField(max_length=12)),
                ('bankAccountNumber', models.CharField(max_length=15)),
                ('ifscCode', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('permanentAddress', models.TextField()),
                ('currentAddress', models.TextField()),
                ('biometricIdNumber', models.CharField(max_length=15)),
                ('intership_tenure', models.CharField(choices=[('emp1', 'Exm1'), ('emp2', 'Exm2')], max_length=10)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('projectWorked', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('V', 'Volunteer'), ('I', 'Intern')], max_length=1)),
                ('tenure', models.CharField(max_length=3)),
                ('joiningDate', models.DateField()),
                ('endDate', models.DateField()),
                ('uploadTrakerLink', models.URLField()),
                ('mentorLeader', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('upload_report', models.FileField(upload_to='files')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('registration_number', models.CharField(editable=False, max_length=225, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='intern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='certificate_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.UserProfile'),
        ),
    ]
